stages:
  - name: build
    transformations:
      - checkout

transformations:
  - name: checkout
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/tcuje/jarvis-test.git
